### PR TITLE
Add RHEL support to collectd config generator config_manager

### PR DESCRIPTION
**Pull request by anmolbabu**
tendrl-bug-id: Tendrl/node-monitoring#47
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
Verified

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat @shtripat Please review

**Comment by r0h4n** [comment]
Need a issue explaining why the PR is required

**Comment by anmolbabu** [comment]
@r0h4n Done

**Pull request merged**
