### PR TITLE
[WIP]Refactoring

### PR DESCRIPTION
**Pull request by anmolbabu**
tendrl-bug-id: Tendrl/node-monitoring#77
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by r0h4n** [comment]
Youll need to file issues with details about this PR

**Comment by anmolbabu** [comment]
TODO:
1. Change gluster volume status usage to using get-state
2. Modify brick utilization to use statvfs for brick utilization..

**Comment by nnDarshan** [comment]
@anmolbabu https://github.com/Tendrl/node-monitoring/pull/76#issuecomment-315696546 

The current brick utilization plugin is using statvfs : https://github.com/Tendrl/node-monitoring/blob/develop/tendrl/node_monitoring/plugins/tendrl_glusterfs_brick_utilization.py#L37

**Comment by anmolbabu** [comment]
>@anmolbabu #76 (comment)

>The current brick utilization plugin is using statvfs : https://github.com/Tendrl/node->monitoring/blob/develop/tendrl/node_monitoring/plugins/tendrl_glusterfs_brick_utilization.py#L37

@nnDarshan I saw that... So that is out of our plate now... :)

**Comment by anmolbabu** [comment]
TODO:

1. More refactoring required to extract out common pieces like get-state parsing, command exec utility etc.. into seperate source..
2. Use the concept of write plugins in collectd instead of a write at plugin level and remove dependency from write-graphite and replace it with custom write to graphite..

**Comment by r0h4n** [comment]
Please send this PR on "master" branch

**Pull request closed without merging**
